### ISSUE TITLE
todo 수정 기능 수정

### ISSUE THREAD

**Issue by Ah-ae** [Ah-ae/fe-sprint-my-todo#1]
### 만들고자 하는 기능
Todo 수정 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ] input.focus() 해결
2. [ ] textarea 엔터키 방어
3. [ ] 수정 데이터 확인

### 예상 작업 시간
6h + @ (현재 시점에서 예측 불가)
